[project]
name = "tcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.4.3",
    "pandas>=2.2.3",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
]
